import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/contexts/ThemeContext";
import "./globals.css";
import "./brutalist.css";
import "../styles/brutalist-card.css";
import "../styles/dark-mode.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add this script to prevent flashing */}
        <script 
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Check if we have dark mode preference in localStorage
                const darkModePreference = localStorage.getItem('darkMode');
                if (darkModePreference === 'true') {
                  document.documentElement.classList.add('dark');
                }
              })()
            `
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
