name: Generate Embeddings

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: production  # Associates this job with the 'production' environment

env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: kpiuiijgrjxsuvpnrwhz

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy github-action-deploy --project-ref $PROJECT_ID
