jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Replace with your environment name

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Linking to Supabase project with ref: $SUPABASE_PROJECT_ID"
          supabase link --project-ref $SUPABASE_PROJECT_ID --debug

      - name: Deploy migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push --debug
