name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: kpiuiijgrjxsuvpnrwhz  # e.g. abcdefghijklmnopqrst

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase
        run: supabase link --project-ref $PROJECT_ID

      - name: Apply Migrations
        run: supabase db push

   ##   - name: Deploy Functions
   ##     run: supabase functions deploy --project-ref $PROJECT_ID
