name: Generate Embeddings

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: production  # Associates this job with the 'production' environment

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Embeddings
        uses: supabase/embeddings-generator@v0.0.5  # Use the latest stable version
        with:
          supabase-url: 'https://kpiuiijgrjxsuvpnrwhz.supabase.co'  # Replace with your Supabase project URL
          supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          openai-key: ${{ secrets.OPENAI_KEY }}
          docs-root-path: 'docs'  # Adjust this path to where your markdown files are located
