name: Deploy Supabase Schema to Prod

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://supabase.com/cli/install | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH
          export PATH="$HOME/.supabase/bin:$PATH"
          supabase --version  # Check if the CLI is installed

      - name: Link to Supabase Prod
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Deploy Migrations to Prod
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase --version  # Double-check CLI installation
          supabase db push
