name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production  # Ensure this matches your GitHub environment name

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --debug

      - name: Deploy migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push --debug
