name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: kpiuiijgrjxsuvpnrwhz

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run DB migrations
        run: supabase db push --project-ref $PROJECT_ID

     ## - name: Deploy Edge Functions
     ##   run: supabase functions deploy --project-ref $PROJECT_ID
